[package]
name = "orbital-traits"
version = "0.1.0"
edition = "2021"

[dependencies]
alkanes-runtime.workspace = true
alkanes-support.workspace = true
metashrew-support.workspace = true
anyhow.workspace = true
orbitals-support = { path = "../../alkanes/orbitals-support" }