[package]
name = "orbital-macros"
version = "0.1.0"
edition = "2021"
description = "Macros for orbital alkanes"
authors = ["flex"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
wasm-bindgen = "0.2.100"